// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouTubeClone.Persistance.Contexts;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(YouTubeCloneDbContext))]
    [Migration("20260613121320_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Channels.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubscriptionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.HasIndex("SubscriptionsId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Channels.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Accessibility")
                        .HasColumnType("int");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ChannelId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId1");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Interactions.UserInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserInteractions");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Playlists.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Accessibility")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Playlists");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Playlist");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Subscriptions.Subscriptions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DomainUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DomainUserId")
                        .IsUnique()
                        .HasFilter("[DomainUserId] IS NOT NULL");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DomainUsers");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Videos.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VideoId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("VideoId1");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Videos.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ChannelId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WatchHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId1");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("WatchHistoryId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.WatchHistories.WatchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("WatchHistories");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserStatus")
                        .HasColumnType("int");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Playlists.ChannelPlaylist", b =>
                {
                    b.HasBaseType("YouTubeClone.Domain.Aggregates.Playlists.Playlist");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ChannelId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ChannelId1");

                    b.HasDiscriminator().HasValue("ChannelPlaylist");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Playlists.CustomPlaylist", b =>
                {
                    b.HasBaseType("YouTubeClone.Domain.Aggregates.Playlists.Playlist");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists", t =>
                        {
                            t.Property("OwnerId")
                                .HasColumnName("CustomPlaylist_OwnerId");
                        });

                    b.HasDiscriminator().HasValue("CustomPlaylist");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Playlists.LikedVideosPlaylist", b =>
                {
                    b.HasBaseType("YouTubeClone.Domain.Aggregates.Playlists.Playlist");

                    b.Property<Guid?>("DomainUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("DomainUserId")
                        .IsUnique()
                        .HasFilter("[DomainUserId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("LikedVideosPlaylist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("YouTubeClone.Domain.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("YouTubeClone.Domain.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YouTubeClone.Domain.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("YouTubeClone.Domain.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Channels.Channel", b =>
                {
                    b.HasOne("YouTubeClone.Domain.Aggregates.Users.User", "Owner")
                        .WithOne("Channel")
                        .HasForeignKey("YouTubeClone.Domain.Aggregates.Channels.Channel", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YouTubeClone.Domain.Aggregates.Subscriptions.Subscriptions", null)
                        .WithMany("Channels")
                        .HasForeignKey("SubscriptionsId");

                    b.OwnsOne("YouTubeClone.Domain.Aggregates.Channels.ChannelProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("ChannelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Avatar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ChannelsDescription")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GreaterImg")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Links")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("SubscribersCount")
                                .HasColumnType("int");

                            b1.HasKey("ChannelId");

                            b1.ToTable("Channels");

                            b1.WithOwner()
                                .HasForeignKey("ChannelId");
                        });

                    b.Navigation("Owner");

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Channels.Post", b =>
                {
                    b.HasOne("YouTubeClone.Domain.Aggregates.Channels.Channel", null)
                        .WithMany("Posts")
                        .HasForeignKey("ChannelId1");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Subscriptions.Subscriptions", b =>
                {
                    b.HasOne("YouTubeClone.Domain.Aggregates.Users.User", null)
                        .WithOne("Subscriptions")
                        .HasForeignKey("YouTubeClone.Domain.Aggregates.Subscriptions.Subscriptions", "DomainUserId");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Users.User", b =>
                {
                    b.OwnsOne("YouTubeClone.Domain.Aggregates.Users.UserCredentials", "Credentials", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("HashedPasswords")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MultiFactorTokens")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId");

                            b1.ToTable("DomainUsers");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("YouTubeClone.Domain.Aggregates.Users.UserProfileInfo", "ProfileInfo", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Avatar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Bio")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ThemePreference")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TopicsInterestedIn")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("UserActualName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId");

                            b1.ToTable("DomainUsers");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Credentials")
                        .IsRequired();

                    b.Navigation("ProfileInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Videos.Comment", b =>
                {
                    b.HasOne("YouTubeClone.Domain.Aggregates.Videos.Comment", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("YouTubeClone.Domain.Aggregates.Videos.Video", null)
                        .WithMany("Comments")
                        .HasForeignKey("VideoId1");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Videos.Video", b =>
                {
                    b.HasOne("YouTubeClone.Domain.Aggregates.Channels.Channel", null)
                        .WithMany("Videos")
                        .HasForeignKey("ChannelId1");

                    b.HasOne("YouTubeClone.Domain.Aggregates.Playlists.Playlist", null)
                        .WithMany("Videos")
                        .HasForeignKey("PlaylistId");

                    b.HasOne("YouTubeClone.Domain.Aggregates.WatchHistories.WatchHistory", null)
                        .WithMany("Videos")
                        .HasForeignKey("WatchHistoryId");

                    b.OwnsOne("YouTubeClone.Domain.Aggregates.Videos.Temporal_Metadata", "TemporalMetadata", b1 =>
                        {
                            b1.Property<Guid>("VideoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("UpateDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("UploadDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UploadStatus")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VideoId");

                            b1.ToTable("Videos");

                            b1.WithOwner()
                                .HasForeignKey("VideoId");
                        });

                    b.OwnsOne("YouTubeClone.Domain.Aggregates.Videos.VideoStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("VideoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DislikesCount")
                                .HasColumnType("int");

                            b1.Property<int>("LikesCount")
                                .HasColumnType("int");

                            b1.Property<int>("WatchCount")
                                .HasColumnType("int");

                            b1.HasKey("VideoId");

                            b1.ToTable("Videos");

                            b1.WithOwner()
                                .HasForeignKey("VideoId");
                        });

                    b.OwnsOne("YouTubeClone.Domain.Aggregates.Videos.video_Descriptive", "Descriptive", b1 =>
                        {
                            b1.Property<Guid>("VideoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Tags")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VideoId");

                            b1.ToTable("Videos");

                            b1.WithOwner()
                                .HasForeignKey("VideoId");
                        });

                    b.OwnsOne("YouTubeClone.Domain.Aggregates.Videos.video_Technical_details", "TechnicalDetails", b1 =>
                        {
                            b1.Property<Guid>("VideoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AudioCodec")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("BitRate")
                                .HasColumnType("int");

                            b1.Property<string>("ContainerFormat")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Duration")
                                .HasColumnType("int");

                            b1.Property<long>("FileSize")
                                .HasColumnType("bigint");

                            b1.Property<float>("FrameRate")
                                .HasColumnType("real");

                            b1.Property<string>("Resolution")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VideoCodec")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VideoId");

                            b1.ToTable("Videos");

                            b1.WithOwner()
                                .HasForeignKey("VideoId");
                        });

                    b.OwnsOne("YouTubeClone.Domain.Aggregates.Videos.video_Basics", "Basics", b1 =>
                        {
                            b1.Property<Guid>("VideoId1")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("PrivacyStatus")
                                .HasColumnType("int");

                            b1.Property<string>("ThumbnailUrl")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VideoId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VideoUrl")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VideoId1");

                            b1.ToTable("Videos");

                            b1.WithOwner()
                                .HasForeignKey("VideoId1");
                        });

                    b.Navigation("Basics")
                        .IsRequired();

                    b.Navigation("Descriptive")
                        .IsRequired();

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("TechnicalDetails")
                        .IsRequired();

                    b.Navigation("TemporalMetadata")
                        .IsRequired();
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.WatchHistories.WatchHistory", b =>
                {
                    b.HasOne("YouTubeClone.Domain.Aggregates.Users.User", "Owner")
                        .WithOne("WatchHistory")
                        .HasForeignKey("YouTubeClone.Domain.Aggregates.WatchHistories.WatchHistory", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Playlists.ChannelPlaylist", b =>
                {
                    b.HasOne("YouTubeClone.Domain.Aggregates.Channels.Channel", null)
                        .WithMany("ChannelPlaylists")
                        .HasForeignKey("ChannelId1");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Playlists.CustomPlaylist", b =>
                {
                    b.HasOne("YouTubeClone.Domain.Aggregates.Users.User", null)
                        .WithMany("CustomPlaylists")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Playlists.LikedVideosPlaylist", b =>
                {
                    b.HasOne("YouTubeClone.Domain.Aggregates.Users.User", null)
                        .WithOne("LikedVideosPlaylist")
                        .HasForeignKey("YouTubeClone.Domain.Aggregates.Playlists.LikedVideosPlaylist", "DomainUserId");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Channels.Channel", b =>
                {
                    b.Navigation("ChannelPlaylists");

                    b.Navigation("Posts");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Playlists.Playlist", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Subscriptions.Subscriptions", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Users.User", b =>
                {
                    b.Navigation("Channel");

                    b.Navigation("CustomPlaylists");

                    b.Navigation("LikedVideosPlaylist")
                        .IsRequired();

                    b.Navigation("Subscriptions")
                        .IsRequired();

                    b.Navigation("WatchHistory")
                        .IsRequired();
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.Videos.Video", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("YouTubeClone.Domain.Aggregates.WatchHistories.WatchHistory", b =>
                {
                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
