version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: yt_clone_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourSecurePassword123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  web:
    image: yt_clone_web_api
    container_name: yt_clone_web_api_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=YouTubeCloneDb;User Id=sa;Password=YourSecurePassword123!;TrustServerCertificate=True;MultipleActiveResultSets=true
      - Cloudinary__CloudName=dmlsdri4l
      - Cloudinary__ApiKey=961752819272573
      - Cloudinary__ApiSecret=yOQWsdXYAdIEGZEU8347wq00Yf0
    depends_on:
      - sqlserver

volumes:
  sqlserver_data:
